### ISSUE TITLE
Crash when open KiteSDK

### ISSUE THREAD

**Issue by fahmihidayah** [OceanLabs/Android-Print-SDK#44]
The app crash suddenly after processing my assets.
Please check the log below : 

05-24 03:14:13.661 1698-1698/? E/CatalogueLoader: Unable to parse JSON product: {"wholesale_cost":{"CAD":"0.0000","EUR":"34.9900","GBP":"24.5000","NZD":"0.0000","AUD":"0.0000","SGD":"0.0000","ZAR":"0.0000","USD":"36.9900"},"sandbox_active":true,"print_in_store":false,"id":266334,"wholesale_shipping_costs":{"USA":{"CAD":"0","EUR":"7.0900","GBP":"5.0000","NZD":"0","AUD":"0","SGD":"0","USD":"7.5000"},"rest_of_world":{"CAD":"0","EUR":"8.0000","GBP":"5.6000","NZD":"0","AUD":"0","SGD":"0","USD":"8.5000"},"GBR":{"CAD":"0","EUR":"7.0900","GBP":"5.0000","NZD":"0","AUD":"0","SGD":"0","USD":"7.5000"},"europe":{"CAD":"0","EUR":"6.6000","GBP":"4.6000","NZD":"0","AUD":"0","SGD":"0","USD":"7.0000"}},"name":"American Apparel Zip Fleece Hoodie","valid_sizes":["S","M","L","XL","XXL"],"description_markdown":"","product_category":"Apparel","template_id":"aa_zip_hoodie","product_active":true,"modification_colors":[1,2,5,7,26,120,317,393],"active":true,"modification_costs":[{"modification__modification_id":"center_back","cost":"5.0000","cost_currency":"GBP"},{"modification__modification_id":"center_back","cost":"7.0000","cost_currency":"EUR"},{"modification__modification_id":"center_back","cost":"7.8000","cost_currency":"USD"},{"modification__modification_id":"center_chest","cost":"5.0000","cost_currency":"GBP"},{"modification__modification_id":"center_chest","cost":"7.0000","cost_currency":"EUR"},{"modification__modification_id":"center_chest","cost":"7.8000","cost_currency":"USD"},{"modification__modification_id":"top_chest","cost":"5.0000","cost_currency":"GBP"},{"modification__modification_id":"top_chest","cost":"7.0000","cost_currency":"EUR"},{"modification__modification_id":"top_chest","cost":"7.8000","cost_currency":"USD"},{"modification__modification_id":"left_chest","cost":"5.0000","cost_currency":"GBP"},{"modification__modification_id":"left_chest","cost":"7.0000","cost_currency":"EUR"},{"modification__modification_id":"left_chest","cost":"7.8000","cost_currency":"USD"},{"modification__modification_id":"right_chest","cost":"5.0000","cost_currency":"GBP"},{"modification__modification_id":"right_chest","cost":"7.0000","cost_currency":"EUR"},{"modification__modification_id":"right_chest","cost":"7.8000","cost_currency":"USD"}],"shipping_costs":{"USA":{"CAD":"0","EUR":"8.50800","GBP":"6.00000","NZD":"0","AUD":"0","SGD":"0","USD":"9.00000"},"rest_of_world":{"CAD":"0","EUR":"9.60000","GBP":"6.72000","NZD":"0","AUD":"0","SGD":"0","USD":"10.20000"},"GBR":{"CAD":"0","EUR":"8.50800","GBP":"6.00000","NZD":"0","AUD":"0","SGD":"0","USD":"9.00000"},"europe":{"CAD":"0","EUR":"7.92000","GBP":"5.52000","NZD":"0","AUD":"0","SGD":"0","USD":"8.40000"}},"description":"American Apparel Zip Fleece Hoodie","product":{"size":{"cm":{"height":0.04,"width":0.04},"inch":{"height":0.01,"width":0.01}},"ios_sdk_product_class":"Apparel","ios_sdk_label_color":[203,86,157],"ios_sdk_product_shots":["https:\/\/s3.amazonaws.com\/sdk-static\/product_photography\/apparel\/cover_hoodie.jpg"],"ios_sdk_cover_photo":"https:\/\/s3.amazonaws.com\/sdk-static\/product_photography\/apparel\/top_level.jpg","ios_sdk_ui_class":"","ios_sdk_product_type":"","pdf_height":2383.93700787,"product_code":"DTG-UH-AA004","pdf_width":1683.77952756},"images_required":1,"resource_uri":"\/v2.0\/template\/aa_zip_hoodie\/","upsell_offers":[],"cost":[{"template":"\/v2.1\/template\/aa_zip_hoodie\/","formatted":"€60.99","id":1109457,"amount":"60.9900","currency":"EUR"},{"template":"\/v2.1\/template\/aa_zip_hoodie\/","formatted":"£42.99","id":1109456,"amount":"42.9900","currency":"GBP"},{"template":"\/v2.1\/template\/aa_zip_hoodie\/","formatted":"$64.99","id":1109455,"amount":"64.9900","currency":"USD"}],"modifications":[4]}
                                                  org.json.JSONException: No value for ios_sdk_class_photo
                                                      at org.json.JSONObject.get(JSONObject.java:389)
                                                      at org.json.JSONObject.getString(JSONObject.java:550)
                                                      at ly.kite.catalogue.CatalogueLoader.parseProducts(CatalogueLoader.java:477)
                                                      at ly.kite.catalogue.CatalogueLoader.onCatalogue(CatalogueLoader.java:772)
                                                      at ly.kite.catalogue.CatalogueLoader.onSuccess(CatalogueLoader.java:611)
                                                    at l
05-24 03:14:13.711 1698-1698/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.pixil.instaarabic, PID: 1698
                                                 java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String ly.kite.address.Country.displayName()' on a null object reference
                                                     at ly.kite.analytics.Analytics.getPropertiesJSONObject(Analytics.java:430)
                                                     at ly.kite.analytics.Analytics.trackSDKLoaded(Analytics.java:486)
                                                     at ly.kite.journey.selection.ChooseProductGroupFragment.onCreateView(ChooseProductGroupFragment.java:119)
                                                     at android.app.Fragment.performCreateView(Fragment.java:2220)
                                                     at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:973)
                                                     at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1148)
                                                     at android.app.BackStackRecord.run(BackStackRecord.java:793)
                                                     at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1535)
                                                     at android.app.FragmentManagerImpl$1.run(FragmentManager.java:482)
                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                     at android.os.Looper.loop(Looper.java:148)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

I use google nexus 5 emulator with android version API 23. Do you have any suggestion?

**Comment by ghost** [comment]
It looks like your emulator is not returning a recognised Locale country code. Can you look in Settings -> Language and let me know what the language is set to?

**Comment by ghost** [comment]
I've pushed a candidate fix into master for this. Please let me know if it works for you.

**Comment by fahmihidayah** [comment]
I use English (UK) but my apps use 2 languages (to change language locally only on the apps), english and arabic. And crash always happen when I switch my language to arabic.

**Comment by fahmihidayah** [comment]
My problem fixed. Just my fault when changed language.
